kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
    name: sc-azure-files
provisioner: kubernetes.io/azure-file
reclaimPolicy: Retain
volumeBindingMode: Immediate
mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=1000
  - gid=1000
  - mfsymlinks
  - cache=strict
  - actimeo=30
parameters:
    skuName: Premium_LRS
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-001
spec:
  storageClassName: sc-azure-files
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      #storage: 5Gi #standard_lrs storage type
      storage: 100Gi #premium_lrs storage type